{{- if and (not .Values.security.certificate.existingSecret) (and .Values.security.certificate.certificate .Values.security.certificate.privateKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-certificate
  labels:
  {{- include "template.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
    tls.crt: {{ .Values.security.certificate.certificate | quote }}
    tls.key: {{ .Values.security.certificate.privateKey | quote }}
{{- end }}
