{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
{{- $sslmode := "disable"}}
{{- if .Values.postgresql.tls.enabled }}
{{- $sslmode := "require" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template.fullname" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s/%s?serverVersion=10&sslmode=%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword $postgresqlServiceName .Values.postgresql.postgresqlDatabase $sslmode | b64enc | quote }}
  {{ else if .Values.postgresql.url  }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{ else }}
  database-url:
  {{ end }}
  app_application_key: {{ .Values.security.applicationKey | b64enc | quote }}

  {{- if or (and .Values.security.certificate.certificate .Values.security.certificate.privateKey) .Values.security.certificate.existingSecret }}
  certificate: {{ "/var/run/certs/tls.crt" | b64enc | quote }}
  private_key: {{ "/var/run/certs/tls.key" | b64enc | quote }}
  {{- end }}

